update zshrc to use sheldon

diff --git a/configs/zshrc b/configs/zshrc
--- a/configs/zshrc
+++ b/configs/zshrc
@@ -4,7 +4,7 @@ if [[ -n "$ZSH_DEBUGRC" ]]; then
 fi
 
 # history settings
-# Add these near the top of your .zshrc, before loading zinit
+# Add these near the top of your .zshrc
 HISTFILE=~/.zsh_history
 HISTSIZE=50000
 SAVEHIST=50000
@@ -43,73 +43,15 @@ function copyfile {
     echo "File path copied to clipboard: $fullpath"
 }
 
-# setup tmux plugin manager
-if [[ ! -e "$HOME/.tmux/plugins/tpm" ]]; then
-  git clone https://github.com/tmux-plugins/tpm "$HOME/.tmux/plugins/tpm"
-fi
-
-
-# install and load zinit
-ZINIT_HOME="${XDG_DATA_HOME:-${HOME}/.local/share}/zinit/zinit.git"
-[ ! -d $ZINIT_HOME ] && mkdir -p "$(dirname $ZINIT_HOME)"
-[ ! -d $ZINIT_HOME/.git ] && git clone https://github.com/zdharma-continuum/zinit.git "$ZINIT_HOME"
-source "${ZINIT_HOME}/zinit.zsh"
-
-
-# Create the directory for cusotm zsh completions
-mkdir -p $HOME/.local/share/custom_zsh_completions
-# add custom completions to cusotm path
-fpath=($HOME/.local/share/custom_zsh_completions $fpath)
-
-
 # Load from cache immediately
 autoload -U compinit
 compinit
 
+# load sheldon plugins
+eval "$(sheldon source)"
 
-# # gcloud completions
-# if command -v gcloud >/dev/null && [[ ! -e "$HOME/.local/google-cloud-sdk" ]]; then
-#   savepath=$(mktemp)
-#   wget https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-cli-linux-x86_64.tar.gz --output-document=$savepath
-#   tar -xf $savepath -C "$HOME/.local"
-# fi
-#
-# gcloud_zsh="$HOME/.local/google-cloud-sdk/completion.zsh.inc"
-# if [[ -e "$gcloud_zsh" ]]; then
-#   source "$gcloud_zsh"
-# fi
-#
-# Plugins
-zinit light z-shell/zsh-navigation-tools
-zinit light zsh-users/zsh-autosuggestions
-zinit light zsh-users/zsh-completions
-zinit light Aloxaf/fzf-tab
-zinit ice wait silent
-zinit light zsh-users/zsh-syntax-highlighting
-zinit ice wait silent
-zinit light MichaelAquilina/zsh-you-should-use
-zinit ice wait silent
-zinit snippet OMZP::colored-man-pages
-zinit ice wait silent
-zinit light xPMo/zsh-ls-colors
-zinit ice wait lucid
-zinit load davidde/git
-zinit ice lucid wait'0'
-zinit light joshskidmore/zsh-fzf-history-search
-zinit ice lucid wait'0'
-zinit light l4u/zsh-output-highlighting
-zinit ice wait lucid pick"flatpak.plugin.zsh" as"completion"
-zinit light bilelmoussaoui/flatpak-zsh-completion
-
-zinit ice pick"lib/async.zsh" src"dracula.zsh-theme"; zinit light dracula/zsh
 # show hostname
 DRACULA_DISPLAY_CONTEXT=1
-
-# WezTerm shell integration with zinit
-if [[ -n "$WEZTERM_PANE" ]]; then
-    zinit ice wait lucid
-    zinit snippet "https://raw.githubusercontent.com/wez/wezterm/main/assets/shell-integration/wezterm.sh"
-fi
 
 # fnm completion and shell
 if command -v fnm >/dev/null; then
@@ -120,33 +62,102 @@ fi
 ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE="fg=#707070,underline"
 
 # custom completions
-zinit wait lucid for \
-    atload"command -v glab >/dev/null && source <(glab completion -s zsh)" \
-    atload"command -v docker >/dev/null && ! uname -r | grep -iq microsoft && source <(docker completion zsh)" \
-    atload"command -v gh >/dev/null && source <(gh completion -s zsh)" \
-    atload"command -v fzf >/dev/null && source <(fzf --zsh)" \
-        zdharma-continuum/null
+if command -v glab >/dev/null; then source <(glab completion -s zsh); fi
+if command -v docker >/dev/null && ! uname -r | grep -iq microsoft; then source <(docker completion zsh); fi
+if command -v gh >/dev/null; then source <(gh completion -s zsh); fi  
+if command -v fzf >/dev/null; then source <(fzf --zsh); fi
 
-# sertup bit warden to BW_SESSION var
-function setup-bw() {
-  if ! command -v jq >/dev/null; then
-    echo "jq not found!"
-    return 1;
-  fi
-
+function bw-setup() {
   current_status="$(bw status | jq -r .status)"
   case $current_status in
       "unauthenticated")
-          echo "Please log in first"
-          bw login
+          echo "Please log in first with 'bw login' before setting up session"
+          return 1
+
           ;;
       "locked")
-          export BW_SESSION=$(bw unlock --raw)
+          echo "locked, please unlock..."
+          unlock_result=$(bw unlock --raw)
+          if [[ "$?" -ne "0" ]]; then
+            echo "Failed to unlock!"
+            return 1
+          fi
+          export BW_SESSION="$unlock_result"
           ;;
       "unlocked")
           echo "Already unlocked"
           ;;
+      *)
+          echo "unknown status $current_status"
+          return 1
+          ;;
   esac
+}
+
+function bw-view() {
+    # get all items from bitwarden
+    bw_items=$(bw list items)
+
+    # pass ID (hidden as 1st col) to fzf with details
+    selected_id=$(jq -r '.[] | .id + " " + .name + " " + .login.username' <<< "$bw_items" | fzf --with-nth 2.. | awk '{print $1}')
+
+    # check user selected an item
+    if test -z "$selected_id"; then
+        echo "no item selected!"
+        return 1
+    fi
+
+    # filter items based on selected ID and convert to yaml
+    jq -r ".[] | select(.id == \"$selected_id\")" <<< "$bw_items" | yq -p=json
+}
+
+function bw-edit() {
+    # get all items from bitwarden
+    bw_items=$(bw list items)
+
+    if test -z bw_items; then
+        return 1
+    fi
+
+    # pass ID (hidden as 1st col) to fzf with details
+    selected_id=$(jq -r '.[] | .id + " " + .name + " " + .login.username' <<< "$bw_items" | fzf --with-nth 2.. | awk '{print $1}')
+
+    # check user selected an item
+    if test -z $selected_id; then
+        echo "no item selected!"
+        return 1
+    fi
+    echo "retrieved ID $selected_id"
+
+    # create temp file
+    tmpfile=$(mktemp)
+
+    # write JSON to temp file
+    jq -r ".[] | select(.id == \"$selected_id\")" <<< "$bw_items" >$tmpfile
+
+    # check file not empty
+    if test -z "$(cat -A $tmpfile)"; then
+        echo "error, json is empty!"
+        return 1
+    fi
+
+    # open in editor (this blocks until editor closes)
+    $EDITOR $tmpfile
+
+    if test "$(cat $tmpfile)" = "$item_json"; then
+        echo "no changes made, exiting..."
+        rm -f $tmpfile
+        return 0
+    fi
+
+    # update bitwarden with edited JSON
+    echo "sending updated JSON to bitwarden..."
+    cat $tmpfile | bw encode | bw edit item $selected_id
+
+    # cleanup
+    rm -f $tmpfile
+
+    echo "Item $selected_id updated successfully"
 }
 
 # control left/right because im lazy and dont want to un-learn
